apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexcer
  labels:
    app: indexcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexcer
  template:
    metadata:
      labels:
        app: indexcer
    spec:
      containers:
        - name: indexcer
          image: username/indexcer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5